"use client";
import Image from "next/image";
import Footer from "@/app/components/ui/footer/footer";
import Navbar from "@/app/components/ui/navbar/navbar";
import { ModelTitle } from "../model-components/modetitle";
import LLMImage from "../../../assets/ModelBg/LLM-Text-Classification-Large.png";
import { Label } from "../../../components/ui/label";
import { Input } from "../../../components/ui/input";
import { cn } from "@/utils/cn";
import { Textarea } from "../../../components/ui/textarea";
import Link from "next/link";

export default function Model() {
  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    console.log("Form submitted");
  };
  return (
    <>
      <Navbar />
      <ModelTitle
        modelImage={LLMImage}
        modelSubtitle="Was the essay written by an LLM or Human?"
        modelTitle="LLM Generated Text Detection"
        modelCategory="Natural Language"
      />
      <section className="w-screen h-screen bg-black">
        <div className="px-20 py-40">
          <h3 className="text-white text-3xl tracking-tight leading-none font-medium">
            Is the text generated by an LLM?
          </h3>
          <h6 className="text-white font-regular pt-3">
            Paste your content below, and we’ll tell you likely it is that it
            has been generated by an LLM
          </h6>
        </div>
        <div className="flex px-20">
          <form className="my-8 w-1/2" onSubmit={handleSubmit}>
            <LabelInputContainer className="mb-8">
              <Label htmlFor="message">Message</Label>
              <Textarea placeholder="Enter your message"></Textarea>
            </LabelInputContainer>
            <div className="flex items-center">
              <button
                className="hover:opacity-[0.8] relative group/btn bg-dark-gray block dark:bg-dark-gray w-56 text-white rounded-md h-10 font-medium shadow-[0px_1px_0px_0px_#ffffff40_inset,0px_-1px_0px_0px_#ffffff40_inset] dark:shadow-[0px_1px_0px_0px_var(--zinc-800)_inset,0px_-1px_0px_0px_var(--zinc-800)_inset]"
                type="submit"
              >
                Send
              </button>
            </div>
          </form>
          <div className="w-1/2"></div>
        </div>
      </section>
      <Footer />
    </>
  );
}

const LabelInputContainer = ({
  children,
  className,
}: {
  children: React.ReactNode;
  className?: string;
}) => {
  return (
    <div className={cn("flex flex-col space-y-2 w-full", className)}>
      {children}
    </div>
  );
};
