import ImageCaptioning from "../assets/CardBg/Image-Captioning.png";
import BirdClassification from "../assets/CardBg/Bird-Classfication.png";
import LLMTextClassification from "../assets/CardBg/LLM-Text-Classification.png";

export const models = [
  {
    id: 1,
    title: "IMAGE CAPTIONING",
    description: "Generate a caption for an image",
    img: ImageCaptioning,
    url: "/",
    isDark: false,
    value: "Computer Vision",
  },
  {
    id: 2,
    title: "LLM GENERATED TEXT CLASSIFICATION",
    description: "Is the text generated by an LLM?",
    img: LLMTextClassification,
    url: "/models/model/llm-text-detector",
    isDark: false,
    value: "Natural Language",
  },
  {
    id: 3,
    title: "BIRD IMAGE CLASSIFICATION",
    description: "Recognising birds based on images",
    img: BirdClassification,
    url: "/",
    isDark: true,
    value: "Computer Vision",
  },
];
